/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'logger',
    path: '/logger',
    component: 'layout.base',
    meta: {
      title: 'logger',
      i18nKey: 'route.logger',
      icon: 'typcn:document-text',
      order: 98
    },
    children: [
      {
        name: 'logger_request',
        path: '/logger/request',
        component: 'view.logger_request',
        meta: {
          title: 'logger_request',
          i18nKey: 'route.logger_request',
          icon: 'fa-brands:tencent-weibo',
          permission: 'logger.request.view'
        }
      },
      {
        name: 'logger_system',
        path: '/logger/system',
        component: 'view.logger_system',
        meta: {
          title: 'logger_system',
          i18nKey: 'route.logger_system',
          icon: 'material-symbols-light:legend-toggle-rounded',
          permission: 'logger.system.view'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(phone-pwd-login|code-login|phone-register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'profile',
    path: '/profile',
    component: 'layout.base$view.profile',
    meta: {
      title: 'profile',
      i18nKey: 'route.profile',
      hideInMenu: true
    }
  },
  {
    name: 'server',
    path: '/server',
    component: 'layout.base',
    meta: {
      title: 'server',
      i18nKey: 'route.server',
      icon: 'eos-icons:storage-class',
      order: 97
    },
    children: [
      {
        name: 'server_redis',
        path: '/server/redis',
        component: 'view.server_redis',
        meta: {
          title: 'server_redis',
          i18nKey: 'route.server_redis',
          icon: 'cib:redis',
          order: 1,
          permission: 'server.redis.view'
        }
      },
      {
        name: 'server_scheduler',
        path: '/server/scheduler',
        component: 'view.server_scheduler',
        meta: {
          title: 'server_scheduler',
          i18nKey: 'route.server_scheduler',
          order: 2,
          icon: 'teenyicons:clock-outline',
          permission: 'server.scheduler.view'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'carbon:cloud-service-management',
      order: 99
    },
    children: [
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role',
          icon: 'carbon:user-role',
          order: 3,
          keepAlive: true,
          permission: 'system.role.view'
        }
      },
      {
        name: 'system_setting',
        path: '/system/setting',
        component: 'view.system_setting',
        meta: {
          title: 'system_setting',
          i18nKey: 'route.system_setting',
          order: 9,
          keepAlive: true,
          icon: 'material-symbols:settings',
          permission: 'system.setting.view'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'ic:round-manage-accounts',
          order: 1,
          keepAlive: true,
          permission: 'system.user.view'
        }
      }
    ]
  }
];
