import { getApiUrl } from '../request';

export const apiUrl = getApiUrl();
export * from './modules/auth';
export * from './modules/route';
export * from './modules/device';
export * from './modules/user-profile';
export * from './modules/user';
export * from './modules/enums';
export * from './modules/role';
export * from './modules/product';
export * from './modules/plan-task';
export * from './modules/js-script';
export * from './modules/dashboard';
export * from './modules/plan-task-settlement';
export * from './modules/device-command';
export * from './modules/category-repeat-purchase';
export * from './modules/common';
export * from './modules/logger';
export * from './modules/tenant';
export * from './modules/tenant-user';
export * from './modules/alipay-lovepay';
export * from './modules/configuration';
export * from './modules/alipay-lovepay-record';
export * from './modules/device-taobao';
export * from './modules/device-alibaba';
export * from './modules/plan-task-comment';
export * from './modules/shop';
export * from './modules/friend';
export * from './modules/device-command';
export * from './modules/network-pairing';
