/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  logger_request: () => import("@/views/logger/request/index.vue"),
  logger_system: () => import("@/views/logger/system/index.vue"),
  profile: () => import("@/views/profile/index.vue"),
  server_redis: () => import("@/views/server/redis/index.vue"),
  server_scheduler: () => import("@/views/server/scheduler/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_setting: () => import("@/views/system/setting/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
