/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  about_doc: () => import("@/views/about/doc/index.vue"),
  about_update: () => import("@/views/about/update/index.vue"),
  alibaba_comment: () => import("@/views/alibaba/comment/index.vue"),
  alibaba_product: () => import("@/views/alibaba/product/index.vue"),
  alibaba_shop: () => import("@/views/alibaba/shop/index.vue"),
  alibaba_task: () => import("@/views/alibaba/task/index.vue"),
  device_alibaba: () => import("@/views/device/alibaba/index.vue"),
  device_douyin: () => import("@/views/device/douyin/index.vue"),
  device_jingdong: () => import("@/views/device/jingdong/index.vue"),
  device_list: () => import("@/views/device/list/index.vue"),
  device_pdd: () => import("@/views/device/pdd/index.vue"),
  device_rednote: () => import("@/views/device/rednote/index.vue"),
  device_taobao: () => import("@/views/device/taobao/index.vue"),
  device_detail: () => import("@/views/device_detail/[id].vue"),
  douyin_comment: () => import("@/views/douyin/comment/index.vue"),
  douyin_product: () => import("@/views/douyin/product/index.vue"),
  douyin_shop: () => import("@/views/douyin/shop/index.vue"),
  douyin_task: () => import("@/views/douyin/task/index.vue"),
  friend_audit: () => import("@/views/friend/audit/index.vue"),
  friend_list: () => import("@/views/friend/list/index.vue"),
  friend_request: () => import("@/views/friend/request/index.vue"),
  home: () => import("@/views/home/index.vue"),
  jingdong_comment: () => import("@/views/jingdong/comment/index.vue"),
  jingdong_product: () => import("@/views/jingdong/product/index.vue"),
  jingdong_shop: () => import("@/views/jingdong/shop/index.vue"),
  jingdong_task: () => import("@/views/jingdong/task/index.vue"),
  logger_request: () => import("@/views/logger/request/index.vue"),
  logger_system: () => import("@/views/logger/system/index.vue"),
  maintain_command: () => import("@/views/maintain/command/index.vue"),
  maintain_script: () => import("@/views/maintain/script/index.vue"),
  pdd_comment: () => import("@/views/pdd/comment/index.vue"),
  pdd_product: () => import("@/views/pdd/product/index.vue"),
  pdd_shop: () => import("@/views/pdd/shop/index.vue"),
  pdd_task: () => import("@/views/pdd/task/index.vue"),
  platform_alipaylovepay: () => import("@/views/platform/alipaylovepay/index.vue"),
  platform_categoryrepeat: () => import("@/views/platform/categoryrepeat/index.vue"),
  platform_setting: () => import("@/views/platform/setting/index.vue"),
  platform_tenant: () => import("@/views/platform/tenant/index.vue"),
  platform_tenantuser: () => import("@/views/platform/tenantuser/index.vue"),
  rednote_comment: () => import("@/views/rednote/comment/index.vue"),
  rednote_product: () => import("@/views/rednote/product/index.vue"),
  rednote_shop: () => import("@/views/rednote/shop/index.vue"),
  rednote_task: () => import("@/views/rednote/task/index.vue"),
  report_alipaylovepay: () => import("@/views/report/alipaylovepay/index.vue"),
  report_alipaylovepayentsettle: () => import("@/views/report/alipaylovepayentsettle/index.vue"),
  report_alipaylovepaypersettle: () => import("@/views/report/alipaylovepaypersettle/index.vue"),
  report_settlement: () => import("@/views/report/settlement/index.vue"),
  system_role: () => import("@/views/system/role/index.vue"),
  system_setting: () => import("@/views/system/setting/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
  taobao_comment: () => import("@/views/taobao/comment/index.vue"),
  taobao_product: () => import("@/views/taobao/product/index.vue"),
  taobao_shop: () => import("@/views/taobao/shop/index.vue"),
  taobao_task: () => import("@/views/taobao/task/index.vue"),
  "user-center": () => import("@/views/user-center/index.vue"),
};
